### ISSUE TITLE
Readme.cpp.md

### ISSUE THREAD

**Issue by justgage** [rgrinberg/opium#43]
I'm not sure what this file is for (I was hoping to do a pull request for some documentation)

Also, if I where to write more comprehensive documentation, is there a place you would like it to be?

**Comment by rgrinberg** [comment]
`README.cpp.md` is what's used to generate the `README.md` file. This processing step is necessary because I like to make sure that all the examples build and are working.

What kind of documentation do you want to write? If you want to write "manual" style documentation I'd suggest creating a doc dir and writing some stuff in markdown. We can worry about presentation later.

If you want to just document the API then ocamldocs are a good place for that.

**Comment by justgage** [comment]
I was going to just add a few more examples to the Readme and maybe even some more manual style docs if I can get around to it.

**Comment by rgrinberg** [comment]
Alright. Then just create some examples, edit `README.cpp.md` and run `$ make README.md`. Let me know if you have any questions.
